<?php

namespace common\models;

use Yii;
use yii\db\ActiveQuery;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "Category".
 *
 * @property int $id
 * @property int $parent
 * @property string $title
 * @property string $text
 * @property ActiveQuery children
 * @property ActiveQuery materials
 */
class Category extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'category';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['title'], 'required'],
            [['parent'], 'integer'],
            [['text'], 'string'],
            [['title'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'parent' => 'Родитель',
            'title' => 'Заголовок',
            'text' => 'Материал',
        ];
    }

    /**
     * @return array
     */
    public function getSelectParent() {
        $categories = self::find();
        $categories = $this->excludeCategory($categories, $this);
        return ArrayHelper::map($categories->all(), 'id', 'title');
    }

    /**
     * @param ActiveQuery $categories
     * @param Category $parent
     * @return ActiveQuery
     */
    private function excludeCategory($categories, $parent) {
        if ($parent->id) {
            $categories->andWhere(['<>', 'id', $parent->id]);
            foreach ($parent->children as $child) {
                $categories = $this->excludeCategory($categories, $child);
            }
        }
        return $categories;
    }

    public function getChildren()
    {
        return $this->hasMany(Category::className(), ['parent' => 'id']);
    }

    public function getMaterials()
    {
        return $this->hasMany(Material::className(), ['parent' => 'id']);
    }


    public function getParent()
    {
        return $this->hasOne(Category::className(), ['id' => 'parent']);
    }

    public static function getSelectParents() {
        $categories = Category::find()
            ->select(['c.id', 'c.title'])
            ->join('JOIN', 'category c', 'category.parent = c.id')
            ->distinct(true)
            ->all();
        return ArrayHelper::map($categories, 'id', 'title');
    }

    public static function getTitle($id) {
        return self::findOne($id)->title;
    }

    public function beforeDelete()
    {
        
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }
}
