<?php

namespace common\models\setting;

use Yii;
use yii\db\ActiveRecord;

/**
 * This is the model class for table "setting".
 *
 * @property int $id
 * @property string $title
 * @property string $description
 * @property string $keywords
 * @property int $price
 * @property Mail $mail
 */
class Setting extends \yii\db\ActiveRecord
{
    public function __construct(array $config = [])
    {
        $this->title = 'Мой сайт';
        parent::__construct($config);
    }

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'setting';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['price'], 'required'],
            [['description', 'keywords'], 'string'],
            [['title'], 'string', 'max' => 255],
            [['price'], 'integer'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Заголовок сайта',
            'description' => 'Описание сайта (не более 160 символов)',
            'keywords' => 'Ключевые слова сайта (не более 250 символов)',
            'price' => 'Цена за день',
        ];
    }

    public function getMail() {
        return $this->hasOne(Mail::className(), ['setting_id' => 'id']);
    }

    /**
     * @return array|Setting|ActiveRecord
     */
    public static function take() {
        return Setting::find()->one();
    }

    public function load($data, $formName = null)
    {
        $this->saveLink($this->mail, $data);
        return parent::load($data, $formName); // TODO: Change the autogenerated stub
    }

    /**
     * @param ActiveRecord $link
     * @param $data
     * @return bool
     */
    private function saveLink($link, $data) {
        return ($link->load($data) && $link->save());
    }
}
